name: 02 - Many Doorbells

on:
  push:
    branches: [main]              # only pushes to main
  workflow_dispatch:              # adds a "Run workflow" button in the Actions tab
  issues:
    types: [opened]               # when someone opens an issue
  schedule:
    - cron: "0 8 * * 1"           # every Monday 08:00 UTC

jobs:
  who-rang:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was woken up by '${{ github.event_name }}' event"
      - run: echo "Triggered by user ${{ github.actor }}"