name: 01 - Hello Workflow        # the name shown in the Actions tab

on: push                          # WHEN (the event)

jobs:                             # WHAT
  hello-again:                      # a job id (you choose the name)
    runs-on: ubuntu-latest        # WHERE (the runner)
    steps:
      - run: echo "Hello again, this is second workflow from sam repo"